-- AlterTable
ALTER TABLE "user" ADD COLUMN     "isVerified" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "verifyCode" UUID NOT NULL DEFAULT 'A0EEBC99-9C0B-4EF8-BB6D-6BB9BD380A11';
ALTER TABLE "user" ALTER COLUMN "verifyCode" DROP DEFAULT;
